name: "Workflow Commands"

on: ['push']

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: "group logging"
        run: |
          echo "::group::My Group Message"
          echo "Msg 1"
          echo "Msg 2"
          echo "::endgroup::"
      - name: "step 1"
        run: |
          echo "my_val=Hello" >> GITHUB_ENV #setting git hub env var value
      - name: "step 2"
        run: |
          echo $my_val   #using github env var value